const Jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Google",
    location: "Remote",
    type: "Full Time",
    salary: "12 LPA",
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "Microsoft",
    location: "Onsite",
    type: "Full Time",
    salary: "15 LPA",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "Amazon",
    location: "Remote",
    type: "Internship",
    salary: "30K/month",
  },
  {
    id: 4,
    title: "React Developer",
    company: "Infosys",
    location: "Hybrid",
    type: "Part Time",
    salary: "7 LPA",
  },
  {
    id: 5,
    title: "Node.js Developer",
    company: "TCS",
    location: "Remote",
    type: "Full Time",
    salary: "8 LPA",
  },
  {
    id: 6,
    title: "Java Developer",
    company: "Wipro",
    location: "Onsite",
    type: "Full Time",
    salary: "9 LPA",
  },
  {
    id: 7,
    title: "Python Developer",
    company: "Accenture",
    location: "Remote",
    type: "Internship",
    salary: "35K/month",
  },
  {
    id: 8,
    title: "Data Analyst",
    company: "IBM",
    location: "Hybrid",
    type: "Full Time",
    salary: "10 LPA",
  },
  {
    id: 9,
    title: "DevOps Engineer",
    company: "Oracle",
    location: "Remote",
    type: "Full Time",
    salary: "14 LPA",
  },
  {
    id: 10,
    title: "Software Engineer",
    company: "Adobe",
    location: "Onsite",
    type: "Full Time",
    salary: "18 LPA",
  },
];

export default Jobs;