const students = [
  {
    id: 1,
    name: "Ariba Hasan",
    course: "B.Tech CSE",
    year: "2nd Year",
    cgpa: 8.9,
    status: "Active",
    image: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "Ali Khan",
    course: "B.Tech IT",
    year: "3rd Year",
    cgpa: 8.2,
    status: "Active",
    image: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 3,
    name: "Sara Ahmed",
    course: "B.Tech CSE",
    year: "1st Year",
    cgpa: 9.4,
    status: "Topper",
    image: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: 4,
    name: "Ayaan Sheikh",
    course: "B.Tech ECE",
    year: "4th Year",
    cgpa: 7.8,
    status: "Active",
    image: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 5,
    name: "Fatima Noor",
    course: "B.Tech CSE",
    year: "2nd Year",
    cgpa: 9.1,
    status: "Topper",
    image: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 6,
    name: "Mohammad Zaid",
    course: "B.Tech ME",
    year: "3rd Year",
    cgpa: 7.5,
    status: "Inactive",
    image: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: 7,
    name: "Hina Parveen",
    course: "B.Tech CE",
    year: "1st Year",
    cgpa: 8.5,
    status: "Active",
    image: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: 8,
    name: "Rahul Kumar",
    course: "B.Tech IT",
    year: "4th Year",
    cgpa: 8.0,
    status: "Active",
    image: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: 9,
    name: "Priya Singh",
    course: "B.Tech CSE",
    year: "3rd Year",
    cgpa: 9.3,
    status: "Topper",
    image: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: 10,
    name: "Ahmed Raza",
    course: "B.Tech AI & DS",
    year: "2nd Year",
    cgpa: 8.7,
    status: "Active",
    image: "https://i.pravatar.cc/150?img=10",
  },
];

export default students;