const Employees = [
  {
    id: 1,
    name: "Ariba Hasan",
    role: "Frontend Developer",
    department: "Engineering",
    salary: 60000,
    experience: 2,
    city: "Patna",
    status: "Active",
  },
  {
    id: 2,
    name: "Aman Kumar",
    role: "Backend Developer",
    department: "Engineering",
    salary: 70000,
    experience: 3,
    city: "Delhi",
    status: "Active",
  },
  {
    id: 3,
    name: "Priya Sharma",
    role: "UI/UX Designer",
    department: "Design",
    salary: 55000,
    experience: 2,
    city: "Bengaluru",
    status: "Active",
  },
  {
    id: 4,
    name: "Rahul Singh",
    role: "QA Engineer",
    department: "Testing",
    salary: 50000,
    experience: 1,
    city: "Lucknow",
    status: "Inactive",
  },
  {
    id: 5,
    name: "Sneha Verma",
    role: "HR Manager",
    department: "Human Resources",
    salary: 65000,
    experience: 5,
    city: "Mumbai",
    status: "Active",
  },
  {
    id: 6,
    name: "Mohit Yadav",
    role: "DevOps Engineer",
    department: "Infrastructure",
    salary: 80000,
    experience: 4,
    city: "Hyderabad",
    status: "Active",
  },
  {
    id: 7,
    name: "Neha Gupta",
    role: "Data Analyst",
    department: "Analytics",
    salary: 62000,
    experience: 3,
    city: "Pune",
    status: "Active",
  },
  {
    id: 8,
    name: "Faizan Ali",
    role: "Mobile Developer",
    department: "Engineering",
    salary: 68000,
    experience: 2,
    city: "Kolkata",
    status: "Inactive",
  },
  {
    id: 9,
    name: "Anjali Mishra",
    role: "Project Manager",
    department: "Management",
    salary: 90000,
    experience: 6,
    city: "Noida",
    status: "Active",
  },
  {
    id: 10,
    name: "Rohan Das",
    role: "Full Stack Developer",
    department: "Engineering",
    salary: 85000,
    experience: 5,
    city: "Chennai",
    status: "Active",
  },
];

export default Employees